name: nvmeas
dependencies:
  - python=2.7
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - ipyparallel
  - dill
  - future
  - pip:
    - git+https://github.com/QInfer/python-qinfer.git@b4c4924c1b06453ff4aa35076e7eea982c8151e1

